<#
.SYNOPSIS
  One-shot, idempotent setup for the Paper training server (task T8).

.DESCRIPTION
  Prepares server/ to run a Paper 1.21.1 build 133 instance tuned for the PvP
  RL training arena:

    1. Downloads paper-1.21.1-133.jar from the PaperMC v2 API (skipped if the
       jar already exists, unless -Force is passed).
    2. Writes eula.txt with eula=true (accepting Mojang's EULA — this is a
       deliberate, recorded action; running the server implies acceptance).
    3. Writes server.properties tuned for headless, deterministic, low-overhead
       training: offline-mode, flat world, no mobs/animals, view/sim distance 2,
       fixed seed, pvp on, gamemode survival, normal difficulty, plus chat
       anti-spam friendliness so the bridge's rapid /tp + /effect commands are
       not throttled or kicked.
    4. Installs the arena datapack into the world's datapacks/ folder so the
       arena/* functions are available on first boot.

  This script does NOT launch the server. Use start.ps1 for that. It is safe to
  re-run: existing files are only overwritten when they are config files we own
  (eula.txt, server.properties) or when -Force is given (the jar).

.PARAMETER Force
  Re-download the Paper jar even if it already exists.

.PARAMETER ServerDir
  Server root. Defaults to the parent of this script's directory (server/).

.EXAMPLE
  pwsh -NoProfile -File server/setup/setup.ps1

.NOTES
  Prerequisites: Java 21+ (this machine has Java 25 — see server/compat_check.md).
  Pinned by Tv: Paper 1.21.1 build 133, channel STABLE.
#>

[CmdletBinding()]
param(
    [switch]$Force,
    [string]$ServerDir
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# --- Pinned constants (from server/compat_check.md / Tv) -------------------
$PaperVersion = '1.21.1'
$PaperBuild   = '133'
$JarName      = "paper-$PaperVersion-$PaperBuild.jar"
$DownloadUrl  = "https://api.papermc.io/v2/projects/paper/versions/$PaperVersion/builds/$PaperBuild/downloads/$JarName"

# Bot accounts that must be opped (mirror bridge/bot.js DEFAULT_BOT_CONFIG and
# server/ops.json). Recorded here only for the operator-facing summary.
$LevelSeed = '8675309'   # fixed seed -> reproducible flat world (logged per spec).

# --- Resolve paths ---------------------------------------------------------
if ([string]::IsNullOrWhiteSpace($ServerDir)) {
    # server/setup/setup.ps1 -> server/ is one level up.
    $ServerDir = Split-Path -Parent $PSScriptRoot
}
$ServerDir = (Resolve-Path -LiteralPath $ServerDir).Path
$JarPath = Join-Path $ServerDir $JarName

Write-Host "[setup] Server directory : $ServerDir"
Write-Host "[setup] Paper jar        : $JarName"
Write-Host "[setup] Download URL     : $DownloadUrl"

# --- 1. Download the Paper jar (idempotent) --------------------------------
if ((Test-Path -LiteralPath $JarPath) -and (-not $Force)) {
    Write-Host "[setup] Jar already present, skipping download (use -Force to refresh)."
}
else {
    Write-Host "[setup] Downloading Paper jar ..."
    # TLS 1.2 for older Windows PowerShell hosts; pwsh 7 already defaults higher.
    try { [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12 } catch {}
    $tmp = "$JarPath.partial"
    Invoke-WebRequest -Uri $DownloadUrl -OutFile $tmp -UseBasicParsing
    Move-Item -LiteralPath $tmp -Destination $JarPath -Force
    Write-Host "[setup] Saved $JarName ($([math]::Round((Get-Item -LiteralPath $JarPath).Length / 1MB, 1)) MB)."
}

# --- 2. eula.txt -----------------------------------------------------------
$eulaPath = Join-Path $ServerDir 'eula.txt'
$eulaBody = @"
# By setting eula=true you agree to the Minecraft EULA:
# https://aka.ms/MinecraftEULA
# Written by server/setup/setup.ps1 (task T8).
eula=true
"@
Set-Content -LiteralPath $eulaPath -Value $eulaBody -Encoding ASCII -NoNewline
Write-Host "[setup] Wrote eula.txt (eula=true)."

# --- 3. server.properties (training-tuned) ---------------------------------
# Tuned for: offline join, flat deterministic world, no ambient entities, tiny
# view/sim distance (the bots and the dummy are always near spawn, so loading
# more chunks is pure CPU/RAM waste — the throughput limit per the project spec),
# pvp enabled, survival, normal difficulty. Anti-spam: max-chat-message-length
# raised and spawn-protection disabled so opped bots can act at spawn.
$serverProps = @"
# Minecraft server properties — training arena (task T8).
# Generated by server/setup/setup.ps1. Idempotent: re-running rewrites this file.
# Rationale for the non-default values lives in server/README.md.

# --- Identity / networking ---
online-mode=false
server-port=25565
server-ip=
network-compression-threshold=256
prevent-proxy-connections=false
enforce-secure-profile=false

# --- World generation (flat, deterministic) ---
level-name=world
level-type=minecraft:flat
level-seed=$LevelSeed
generate-structures=false
generator-settings={}
allow-nether=false
allow-flight=true

# --- Gameplay ---
gamemode=survival
force-gamemode=true
difficulty=normal
pvp=true
hardcore=false
spawn-monsters=false
spawn-animals=false
spawn-npcs=false
spawn-protection=0

# --- Performance (bots stay at spawn; load nothing extra) ---
view-distance=2
simulation-distance=2
entity-broadcast-range-percentage=100
max-players=20
player-idle-timeout=0
sync-chunk-writes=true

# --- Chat / anti-spam friendliness for the bridge bots ---
# The bridge fires rapid /tp + /effect clear + regear bursts on every reset.
# Keep message length generous; never rate-limit or kick for "spam".
max-chat-message-length=2048

# --- Misc ---
white-list=false
enable-command-block=true
function-permission-level=2
op-permission-level=4
broadcast-console-to-ops=true
broadcast-rcon-to-ops=true
enable-rcon=false
enable-query=false
motd=Minecraft PvP RL training arena (T8)
"@
$propsPath = Join-Path $ServerDir 'server.properties'
Set-Content -LiteralPath $propsPath -Value $serverProps -Encoding ASCII
Write-Host "[setup] Wrote server.properties (offline, flat, view/sim=2, pvp=true)."

# --- 4. Install the arena datapack into the world --------------------------
# Paper reads datapacks from <level-name>/datapacks/. The pack source of truth
# lives in server/arena/; we copy it in so it is enabled on first world gen.
$datapackSrc = Join-Path $ServerDir 'arena'
$worldDatapacks = Join-Path (Join-Path $ServerDir 'world') 'datapacks'
$datapackDst = Join-Path $worldDatapacks 'arena'
if (Test-Path -LiteralPath $datapackSrc) {
    New-Item -ItemType Directory -Force -Path $worldDatapacks | Out-Null
    # Copy only the datapack payload (pack.mcmeta + data/), not the README.
    Copy-Item -LiteralPath (Join-Path $datapackSrc 'pack.mcmeta') -Destination (Join-Path $worldDatapacks 'arena') -Force -ErrorAction SilentlyContinue
    if (Test-Path -LiteralPath $datapackDst) { Remove-Item -LiteralPath $datapackDst -Recurse -Force }
    New-Item -ItemType Directory -Force -Path $datapackDst | Out-Null
    Copy-Item -LiteralPath (Join-Path $datapackSrc 'pack.mcmeta') -Destination $datapackDst -Force
    Copy-Item -LiteralPath (Join-Path $datapackSrc 'data') -Destination $datapackDst -Recurse -Force
    Write-Host "[setup] Installed arena datapack -> $datapackDst"
    Write-Host "[setup]   (run /reload or /datapack enable after first boot if added live)"
}
else {
    Write-Warning "[setup] server/arena not found; skipped datapack install."
}

Write-Host ""
Write-Host "[setup] Done. Next steps:"
Write-Host "[setup]   1) pwsh -NoProfile -File server/setup/start.ps1   # launch the server"
Write-Host "[setup]   2) In-game/console: /datapack list   (expect 'file/arena' enabled)"
Write-Host "[setup]   3) Op the bots are already declared in server/ops.json:"
Write-Host "[setup]        learner_bot, dummy_bot @ level 4 (offline UUIDs)."
