#!/usr/bin/env bash
# setup.sh — POSIX/bash setup for the Paper training server (task T8).
#
# Linux/macOS counterpart of setup.ps1, for the CPU-heavy cloud VMs that host
# parallel arenas (project spec §9). Idempotent: re-running only rewrites the
# config files we own and skips the jar download if it already exists.
#
# It:
#   1. Downloads paper-1.21.1-133.jar from the PaperMC v2 API (skip if present;
#      FORCE=1 to refresh).
#   2. Writes eula.txt (eula=true — accepting the Mojang EULA).
#   3. Writes a training-tuned server.properties (offline, flat, no mobs,
#      view/sim distance 2, fixed seed, pvp on, survival, normal difficulty,
#      anti-spam friendly).
#   4. Installs the arena datapack into world/datapacks/.
#
# It does NOT launch the server — use start.sh.
#
# Prerequisites: Java 21+ (this machine has Java 25 — see server/compat_check.md)
#                and curl. Pinned by Tv: Paper 1.21.1 build 133, channel STABLE.

set -euo pipefail

# --- Pinned constants (from server/compat_check.md / Tv) -------------------
PAPER_VERSION="1.21.1"
PAPER_BUILD="133"
JAR_NAME="paper-${PAPER_VERSION}-${PAPER_BUILD}.jar"
DOWNLOAD_URL="https://api.papermc.io/v2/projects/paper/versions/${PAPER_VERSION}/builds/${PAPER_BUILD}/downloads/${JAR_NAME}"
LEVEL_SEED="8675309"   # fixed seed -> reproducible flat world (logged per spec).

# --- Resolve paths ---------------------------------------------------------
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
SERVER_DIR="${SERVER_DIR:-$(cd -- "${SCRIPT_DIR}/.." >/dev/null 2>&1 && pwd)}"
JAR_PATH="${SERVER_DIR}/${JAR_NAME}"
FORCE="${FORCE:-0}"

echo "[setup] Server directory : ${SERVER_DIR}"
echo "[setup] Paper jar        : ${JAR_NAME}"
echo "[setup] Download URL     : ${DOWNLOAD_URL}"

# --- 1. Download the Paper jar (idempotent) --------------------------------
if [[ -f "${JAR_PATH}" && "${FORCE}" != "1" ]]; then
    echo "[setup] Jar already present, skipping download (FORCE=1 to refresh)."
else
    echo "[setup] Downloading Paper jar ..."
    curl -fL --retry 3 -o "${JAR_PATH}.partial" "${DOWNLOAD_URL}"
    mv -f "${JAR_PATH}.partial" "${JAR_PATH}"
    echo "[setup] Saved ${JAR_NAME}."
fi

# --- 2. eula.txt -----------------------------------------------------------
cat > "${SERVER_DIR}/eula.txt" <<'EOF'
# By setting eula=true you agree to the Minecraft EULA:
# https://aka.ms/MinecraftEULA
# Written by server/setup/setup.sh (task T8).
eula=true
EOF
echo "[setup] Wrote eula.txt (eula=true)."

# --- 3. server.properties (training-tuned) ---------------------------------
cat > "${SERVER_DIR}/server.properties" <<EOF
# Minecraft server properties — training arena (task T8).
# Generated by server/setup/setup.sh. Idempotent: re-running rewrites this file.
# Rationale for the non-default values lives in server/README.md.

# --- Identity / networking ---
online-mode=false
server-port=25565
server-ip=
network-compression-threshold=256
prevent-proxy-connections=false
enforce-secure-profile=false

# --- World generation (flat, deterministic) ---
level-name=world
level-type=minecraft:flat
level-seed=${LEVEL_SEED}
generate-structures=false
generator-settings={}
allow-nether=false
allow-flight=true

# --- Gameplay ---
gamemode=survival
force-gamemode=true
difficulty=normal
pvp=true
hardcore=false
spawn-monsters=false
spawn-animals=false
spawn-npcs=false
spawn-protection=0

# --- Performance (bots stay at spawn; load nothing extra) ---
view-distance=2
simulation-distance=2
entity-broadcast-range-percentage=100
max-players=20
player-idle-timeout=0
sync-chunk-writes=true

# --- Chat / anti-spam friendliness for the bridge bots ---
max-chat-message-length=2048

# --- Misc ---
white-list=false
enable-command-block=true
function-permission-level=2
op-permission-level=4
broadcast-console-to-ops=true
broadcast-rcon-to-ops=true
enable-rcon=false
enable-query=false
motd=Minecraft PvP RL training arena (T8)
EOF
echo "[setup] Wrote server.properties (offline, flat, view/sim=2, pvp=true)."

# --- 4. Install the arena datapack into the world --------------------------
DATAPACK_SRC="${SERVER_DIR}/arena"
WORLD_DATAPACKS="${SERVER_DIR}/world/datapacks"
DATAPACK_DST="${WORLD_DATAPACKS}/arena"
if [[ -d "${DATAPACK_SRC}" ]]; then
    mkdir -p "${WORLD_DATAPACKS}"
    rm -rf "${DATAPACK_DST}"
    mkdir -p "${DATAPACK_DST}"
    cp "${DATAPACK_SRC}/pack.mcmeta" "${DATAPACK_DST}/pack.mcmeta"
    cp -r "${DATAPACK_SRC}/data" "${DATAPACK_DST}/data"
    echo "[setup] Installed arena datapack -> ${DATAPACK_DST}"
else
    echo "[setup] WARNING: server/arena not found; skipped datapack install." >&2
fi

echo ""
echo "[setup] Done. Next: server/setup/start.sh"
